name: 10. Testing Workflow

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      # Push events on develop branch
      - develop

jobs:
  runs-on: ubuntu-latest

    steps:
      - name: TWF
        run: |
          echo "Sleeping 30 seconds"
          sleep 30
          echo "twff-ing"

