name: 10. Testing Workflow

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      # Push events on develop branch
      - develop

jobs:
  testing_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Call Deploy Workflow
        uses: ./.github/workflows/11_Deploy_workflow_run.yml
