name: 11. Workflow Run Event
on:
  workflow_run:
    workflows: ["10. Testing Workflow"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Application
        run: |
          echo "Starting Deploying the Application"
          echo "Application Deployed"