name: arrow

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - develop

jobs:
  arrowing:
    runs-on: ubuntu-latest
    - uses: ./.github/workflows/triggering.yml  # Reference reusable workflow
