name: Commenting on PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  comment-message:
    runs-on: ubuntu-latest
    if: true
    steps:
      - name: Add comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Thanks for submitting this pull request :tada:!