## Contains jobs corresponding to Oppiabot.
#
#name: Oppiabot
#
#on:
#  pull_request_target:
#    branches:
#      - develop
#
#jobs:
#  oppiabot:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: CLA Check
#        uses: oppia/oppiabot@1.4.0
#        with:
#          repo-token: ${{secrets.GITHUB_TOKEN}}
#        env:
#          SHEETS_TOKEN: ${{ secrets.SHEETS_TOKEN }}
#          SHEETS_CRED: ${{ secrets.SHEETS_CRED }}
#          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}

name: Oppia bot Workflow

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      # Push events on develop branch
      - develop

jobs:
  oppia:
    runs-on: ubuntu-latest

    steps:
      - name: Oppia
        run: |
          echo "Sleeping 30 seconds"
          sleep 30
          echo "Oppia-ing"

