name: test1

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - develop

jobs:
  test1:
    name: Run tests1
    runs-on: ubuntu-latest
    steps:
      - name: Running Test1
        run: |
          echo "Running test 1"
          sleep 30
          echo "Slept for 30 seconds"

