name: Trigger After Static Checks

on:
  workflow_run:
    workflows: [Unit Tests (Robolectric - Bazel)]
    types:
      - completed
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Trigger
        run: echo "Triggering"
