name: Trigger After Static Checks

on:
  workflow_run:
    workflows: [Static Checks]
    types:
      - completed

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger
        run: echo "Triggering"
